theme: jekyll-theme-tactile
title: Sam Ostrander
project-name: Sam Ostrander
project-tagline: Software Developer
description: Software Developer

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
